onEvent('recipes', event => {
  event.recipes.createMilling(Item.of('3x kubejs:quartz_seed'), 'minecraft:quartz')
  event.recipes.createMilling(Item.of('3x kubejs:redstone_seed'), 'create:rose_quartz')
  event.recipes.createMilling(Item.of('3x ae2:certus_crystal_seed'), 'ae2:certus_quartz_crystal')
  event.recipes.create.milling('4x kubejs:rune_dust', 'forbidden_arcanus:rune')
  event.recipes.create.milling('kubejs:powdered_flint', "minecraft:flint")
  event.recipes.create.cutting('ae2:certus_quartz_dust', "ae2:certus_quartz_crystal")
  event.recipes.create.milling(Item.of('minecraft:sand').withChance(0.33), "minecraft:gravel")
  event.recipes.create.milling(['create:powdered_obsidian',Item.of('create:powdered_obsidian',1).withChance(0.50)],'minecraft:obsidian').processingTime(200)
  event.recipes.create.milling('3x thermal:blizz_powder', 'thermal:blizz_rod')
  event.recipes.create.milling('3x thermal:basalz_powder', 'thermal:basalz_rod')
  event.recipes.create.milling('3x thermal:blitz_powder', 'thermal:blitz_rod')
  event.recipes.thermal.pulverizer([Item.of('ars_nouveau:source_gem').withChance(0.33), 'kubejs:sourcegem_fragments'], 'ars_nouveau:source_gem')
  event.recipes.create.milling(['2x quark:red_corundum_cluster',Item.of('quark:red_corundum_cluster',2).withChance(0.50)],'quark:red_corundum')
  event.recipes.create.milling(['2x quark:orange_corundum_cluster',Item.of('quark:orange_corundum_cluster',2).withChance(0.50)],'quark:orange_corundum')
  event.recipes.create.milling(['2x quark:yellow_corundum_cluster',Item.of('quark:yellow_corundum_cluster',2).withChance(0.50)],'quark:yellow_corundum')
  event.recipes.create.milling(['2x quark:green_corundum_cluster',Item.of('quark:green_corundum_cluster',2).withChance(0.50)],'quark:green_corundum')
  event.recipes.create.milling(['2x quark:blue_corundum_cluster',Item.of('quark:blue_corundum_cluster',2).withChance(0.50)],'quark:blue_corundum')
  event.recipes.create.milling(['2x quark:indigo_corundum_cluster',Item.of('quark:indigo_corundum_cluster',2).withChance(0.50)],'quark:indigo_corundum')
  event.recipes.create.milling(['2x quark:violet_corundum_cluster',Item.of('quark:violet_corundum_cluster',2).withChance(0.50)],'quark:violet_corundum')
  event.recipes.create.milling(['2x quark:white_corundum_cluster',Item.of('quark:white_corundum_cluster',2).withChance(0.50)],'quark:white_corundum')
  event.recipes.create.milling(['2x quark:black_corundum_cluster',Item.of('quark:black_corundum_cluster',2).withChance(0.50)],'quark:black_corundum')
})
